const prefix = '/Assets/Icons';
export const IconsPaths = {
  BdAbortIcon: `${prefix}/BdAbortIcon.svg`,
  BdFilledAbortIcon: `${prefix}/BdFilledAbortIcon.svg`,
  BdAlertIcon: `${prefix}/BdAlertIcon.svg`,
  BdAlertErrorIcon: `${prefix}/BdAlertErrorIcon.svg`,
  BdArrowIcon: `${prefix}/BdArrowIcon.svg`,
  BdCalendarIcon: `${prefix}/BdCalendarIcon.svg`,
  BdCloseIcon: `${prefix}/BdCloseIcon.svg`,
  BdCaretIcon: `${prefix}/BdCaretIcon.svg`,
  BdFilterIcon: `${prefix}/BdFilterIcon.svg`,
  BdDotIcon: `${prefix}/BdDotIcon.svg`,
  BdDownloadIcon: `${prefix}/BdDownloadIcon.svg`,
  BdPlusIcon: `${prefix}/BdPlusIcon.svg`,
  BdSearchIcon: `${prefix}/BdSearchIcon.svg`,
  BdVisibleIcon: `${prefix}/BdVisibleIcon.svg`,
  BdNotVisibleIcon: `${prefix}/BdNotVisibleIcon.svg`,
  BdInProgressIcon: `${prefix}/BdInProgressIcon.svg`,
  BdOnGoingIcon: `${prefix}/BdOnGoingIcon.svg`,
  BdFilledOnGoingIcon: `${prefix}/BdFilledOnGoingIcon.svg`,
  BdCompletedIcon: `${prefix}/BdCompletedIcon.svg`,
  BdFilledCompletedIcon: `${prefix}/BdFilledCompletedIcon.svg`,
  BdWaitingIcon: `${prefix}/BdWaitingIcon.svg`,
  BdFilledWaitingIcon: `${prefix}/BdFilledWaitingIcon.svg`,
};
